# Q1

In [1]:
import pandas as pd

In [21]:
df=pd.read_csv("Cutlets.csv")
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [12]:
df.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [13]:
df1=pd.Series(df.iloc[:,0])
df1.head()

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [16]:
df1.mean()

7.01909142857143

In [20]:
df2=pd.Series(df.iloc[:,1])
df2.head()

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
Name: Unit B, dtype: float64

In [22]:
df2.mean()

6.964297142857142

# Mean of the both unit cutlet samples are near to eqal.

# lets assuming for 95% confidence interval and significance level of 5%,

### ..>Null hyposthesis as Ho: μ1 = μ2 (There is no difference in diameters of cutlets between two units). ..>Thus Alternate hypothesis as Ha: μ1 ≠ μ2 (There is significant difference in diameters of cutlets between two units) 2 Sample 2 Tail test applicable

In [27]:
from scipy import stats
import numpy as np
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
p_value=stats.ttest_ind(df1,df2)
np.round(p_value,4)

array([0.7229, 0.4722])

## Answer: so we accept the null hypothesis because the mean of the unitA and UnitB are almost eqaul and p_values greater than the alpha value

# Q2

In [31]:
tat=pd.read_csv("Labtat.csv")
tat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [32]:
tat.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [34]:
tat.isnull().count()

Laboratory 1    120
Laboratory 2    120
Laboratory 3    120
Laboratory 4    120
dtype: int64

In [36]:
#here the columns are more then 2 hence we have to use anova test

In [38]:
tat1 = stats.f_oneway(tat.iloc[:,0],tat.iloc[:,1],tat.iloc[:,2],tat.iloc[:,3])
tat1

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

## here the pvalue is < alpha         

## hence we reject null hypothesis

# Q3

In [40]:
df=pd.read_csv("Buyerratio.csv")

In [41]:
df_table=df.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [42]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [48]:
table=stats.chi2_contingency(df_table)
table

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

### here pvalue is > alpha


## so we accept null hypothesis

# Q4

In [50]:
da=pd.read_csv("Costomer+OrderForm.csv")
da

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [53]:
print(da['Phillippines'].value_counts(),da['Indonesia'].value_counts(),da['Malta'].value_counts(),da['India'].value_counts())
 

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64


In [54]:
df=([[271,267,269,280],[29,33,31,20]])

In [55]:
df

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [56]:
stats.chi2_contingency(df)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [58]:
#here p value is  0.2771020991233135

## hence pvalue is greater than alpha

# hence we accept null hypothesis